# Generated by Django 4.0.3 on 2022-03-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Available', 'Available')], default=True, max_length=200),
        ),
    ]
