# Generated by Django 4.0.3 on 2022-03-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='receipt',
            field=models.CharField(choices=[('CREATINE', 'CREATINE'), ('VITAMINS', 'VITAMINS'), ('PREGNANCY', 'PREGNANCY'), ('COVID', 'COVID'), ('BLOOD', 'BLOOD'), ('X-RAY', 'X-RAY')], max_length=200, null=True),
        ),
    ]
